services:
  # backendコンテナ
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      # DBの接続先情報
      - DATABASE_URL=${DATABASE_URL}
      # CORSの許可するオリジン
      - CORS_ORIGINS=${CORS_ORIGINS}
