export type TopicCandidate = {
  topic: string;
  positionA: string;
  positionB: string;
  category: string;
};

/**
 * お題候補からランダムに1件選び、候補から取り除く
 *
 * @param topicList 残っているお題候補（この配列自体が変更される）
 */
export const pickTopic = (topicList: TopicCandidate[]): TopicCandidate => {
  const index = Math.floor(Math.random() * topicList.length);
  const [picked] = topicList.splice(index, 1);
  return picked;
};

export const TOPICPOOL: TopicCandidate[] = [
  {
    topic: 'これから毎日同じものしか食べられないなら、焼肉よりも寿司が良い',
    positionA: '毎日焼肉を食べるのが良い',
    positionB: '毎日寿司を食べるのが良い',
    category: '生活',
  },
  {
    topic: '生活リズムは、夜型よりも朝型が良い',
    positionA: '朝型の生活が良い',
    positionB: '夜型の生活が良い',
    category: '生活',
  },
  {
    topic: 'お風呂は、シャワーだけよりも湯船につかるのが良い',
    positionA: 'お風呂は湯船につかるのが良い',
    positionB: 'お風呂はシャワーで済ませるのが良い',
    category: '生活',
  },
  {
    topic: '部屋は、好きな物に囲まれるよりもミニマルが良い',
    positionA: '部屋はミニマルが良い',
    positionB: '部屋は好きな物に囲まれるのが良い',
    category: '生活',
  },
  {
    topic: '住むなら、田舎よりも都会が良い',
    positionA: '住むなら都会が良い',
    positionB: '住むなら田舎が良い',
    category: '生活',
  },
  {
    topic: '暮らすなら、賃貸住宅よりも持ち家が良い',
    positionA: '暮らすなら持ち家が良い',
    positionB: '暮らすなら賃貸住宅が良い',
    category: '生活',
  },
  {
    topic: '支払い方法は、現金よりもキャッシュレスが良い',
    positionA: '支払い方法はキャッシュレスが良い',
    positionB: '支払い方法は現金が良い',
    category: '生活',
  },
  {
    topic: '買い物は、ネット通販よりも実店舗が良い',
    positionA: '買い物は実店舗が良い',
    positionB: '買い物はネット通販が良い',
    category: '生活',
  },
  {
    topic: 'お金は、モノを買うよりも体験に使うのが良い',
    positionA: 'お金は体験に使うのが良い',
    positionB: 'お金はモノを買うのに使うのが良い',
    category: '生活',
  },
  {
    topic: '支払いは、キャッシュレスよりも現金が良い',
    positionA: '支払いは現金が良い',
    positionB: '支払いはキャッシュレスが良い',
    category: '生活',
  },
  {
    topic: '寝るなら、ベッドよりも布団が良い',
    positionA: '寝るなら布団が良い',
    positionB: '寝るならベッドが良い',
    category: '生活',
  },
  {
    topic: '休日は、外で活動するよりも家でのんびり過ごすのが良い',
    positionA: '休日は家でのんびり過ごすのが良い',
    positionB: '休日は外で活動するのが良い',
    category: '生活',
  },
  {
    topic: '洗濯物は、部屋干しよりも外干しが良い',
    positionA: '洗濯物は外干しが良い',
    positionB: '洗濯物は部屋干しが良い',
    category: '生活',
  },
  {
    topic: '服は、流行を追うよりも定番のシンプルなものが良い',
    positionA: '服は定番のシンプルなものが良い',
    positionB: '服は流行を取り入れるのが良い',
    category: '生活',
  },
  {
    topic: '掃除は、まとめて一気にやるよりもこまめに少しずつやるのが良い',
    positionA: '掃除はこまめに少しずつやるのが良い',
    positionB: '掃除はまとめて一気にやるのが良い',
    category: '生活',
  },
  {
    topic: '靴は、デザインよりも歩きやすさで選ぶのが良い',
    positionA: '靴は歩きやすさで選ぶのが良い',
    positionB: '靴はデザインで選ぶのが良い',
    category: '生活',
  },
  {
    topic: '家事は、気づいた人がやるよりも担当を決めるのが良い',
    positionA: '家事は担当を決めるのが良い',
    positionB: '家事は気づいた人がやるのが良い',
    category: '生活',
  },
  {
    topic: '住むなら、低層階よりも高層階が良い',
    positionA: '住むなら高層階が良い',
    positionB: '住むなら低層階が良い',
    category: '生活',
  },
  {
    topic: '季節は、冬よりも夏が良い',
    positionA: '夏が良い',
    positionB: '冬が良い',
    category: '季節・自然',
  },
  {
    topic: '季節は、秋よりも春が良い',
    positionA: '春が良い',
    positionB: '秋が良い',
    category: '季節・自然',
  },
  {
    topic: 'お花見は、昼よりも夜が良い',
    positionA: 'お花見は夜が良い',
    positionB: 'お花見は昼が良い',
    category: '季節・自然',
  },
  {
    topic: 'ペットにするなら、猫よりも犬が良い',
    positionA: 'ペットにするなら犬が良い',
    positionB: 'ペットにするなら猫が良い',
    category: '動物',
  },
  {
    topic: '本は、電子書籍よりも紙で読むのが良い',
    positionA: '本は紙で読むのが良い',
    positionB: '本は電子書籍で読むのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'ゾンビから逃げる時に持つなら、傘よりもフライパンが良い',
    positionA: '傘を持つのが良い',
    positionB: 'フライパンを持つのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '音楽は、音源で聴くよりもライブで聴くのが良い',
    positionA: '音楽はライブで聴くのが良い',
    positionB: '音楽は音源で聴くのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '洋画は、吹き替えよりも字幕で観るのが良い',
    positionA: '洋画は字幕で観るのが良い',
    positionB: '洋画は吹き替えで観るのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'アニメを見るなら、毎週見るよりも一気に見るのが良い',
    positionA: 'アニメは一気に見るのが良い',
    positionB: 'アニメは毎週見るのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'ゲームは、みんなでわいわい遊ぶよりも一人でじっくり遊ぶのが良い',
    positionA: 'ゲームは一人でじっくり遊ぶのが良い',
    positionB: 'ゲームはみんなでわいわい遊ぶのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'マンガは、毎週連載を追うよりもまとめて一気読みするのが良い',
    positionA: 'マンガはまとめて一気読みするのが良い',
    positionB: 'マンガは毎週連載を追うのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '物語の結末は、切ない余韻を残すよりもハッピーエンドが良い',
    positionA: '物語はハッピーエンドが良い',
    positionB: '物語は切ない余韻を残す結末が良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'スポーツは、観るよりも自分でやる方が良い',
    positionA: 'スポーツは自分でやる方が良い',
    positionB: 'スポーツは観る方が良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'テレビ番組は、録画や配信で観るよりもリアルタイムで観るのが良い',
    positionA: 'テレビ番組はリアルタイムで観るのが良い',
    positionB: 'テレビ番組は録画や配信で観るのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '楽器を始めるなら、ギターよりもピアノが良い',
    positionA: '楽器を始めるならピアノが良い',
    positionB: '楽器を始めるならギターが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'アウトドアなら、日帰りハイキングよりもキャンプが良い',
    positionA: 'アウトドアならキャンプが良い',
    positionB: 'アウトドアなら日帰りハイキングが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '映画を観るなら、アクションよりもコメディが良い',
    positionA: '映画はコメディが良い',
    positionB: '映画はアクションが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '謎解きを楽しむなら、脱出ゲームよりも推理小説が良い',
    positionA: '謎解きは推理小説で楽しむのが良い',
    positionB: '謎解きは脱出ゲームで楽しむのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '遊園地では、ゆったり系よりも絶叫系のアトラクションが良い',
    positionA: '遊園地では絶叫系が良い',
    positionB: '遊園地ではゆったり系が良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '夏のイベントなら、花火大会よりも夏フェスが良い',
    positionA: '夏のイベントは夏フェスが良い',
    positionB: '夏のイベントは花火大会が良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '遊ぶなら、テレビゲームよりもボードゲームが良い',
    positionA: '遊ぶならボードゲームが良い',
    positionB: '遊ぶならテレビゲームが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '観戦するなら、サッカーよりも野球が良い',
    positionA: '観戦するなら野球が良い',
    positionB: '観戦するならサッカーが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '映画を観るなら、名作を観返すよりも新作を観るのが良い',
    positionA: '映画は新作を観るのが良い',
    positionB: '映画は名作を観返すのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: 'カラオケは、一人で行くよりもみんなで行くのが良い',
    positionA: 'カラオケはみんなで行くのが良い',
    positionB: 'カラオケは一人で行くのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '運動するなら、ランニングよりも筋トレが良い',
    positionA: '運動するなら筋トレが良い',
    positionB: '運動するならランニングが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '習い事を始めるなら、スポーツ系よりも文化系が良い',
    positionA: '習い事は文化系が良い',
    positionB: '習い事はスポーツ系が良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '料理を趣味にするなら、食事作りよりもお菓子作りが良い',
    positionA: '料理を趣味にするならお菓子作りが良い',
    positionB: '料理を趣味にするなら食事作りが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '趣味を楽しむなら、仲間と交流するよりも一人で集中するのが良い',
    positionA: '趣味は一人で集中するのが良い',
    positionB: '趣味は仲間と交流するのが良い',
    category: '趣味・エンタメ',
  },
  {
    topic: '商品を買うなら、中古品よりも新品が良い',
    positionA: '商品を買うなら新品が良い',
    positionB: '商品を買うなら中古品が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'タイムマシンで行くなら、未来よりも過去が良い',
    positionA: 'タイムマシンで行くなら過去が良い',
    positionB: 'タイムマシンで行くなら未来が良い',
    category: '思考実験',
  },
  {
    topic: '超能力を一つ選ぶなら、瞬間移動よりも空を飛ぶ能力が良い',
    positionA: '選ぶなら空を飛ぶ能力が良い',
    positionB: '選ぶなら瞬間移動が良い',
    category: '思考実験',
  },
  {
    topic: '話せるようになるなら、世界中の言語よりも動物の言葉が良い',
    positionA: '動物の言葉を話せるようになる方が良い',
    positionB: '世界中の言語を話せるようになる方が良い',
    category: '思考実験',
  },
  {
    topic: '手に入れるなら、無限の体力よりも完璧な記憶力が良い',
    positionA: '手に入れるなら完璧な記憶力が良い',
    positionB: '手に入れるなら無限の体力が良い',
    category: '思考実験',
  },
  {
    topic: '生まれ変わるなら、魚よりも鳥が良い',
    positionA: '生まれ変わるなら鳥が良い',
    positionB: '生まれ変わるなら魚が良い',
    category: '思考実験',
  },
  {
    topic: '一日だけ手に入れるなら、透明人間よりも時間停止の能力が良い',
    positionA: '時間停止の能力が良い',
    positionB: '透明人間になれる能力が良い',
    category: '思考実験',
  },
  {
    topic: '手に入れるなら、過去を変える力よりも未来を見る力が良い',
    positionA: '手に入れるなら未来を見る力が良い',
    positionB: '手に入れるなら過去を変える力が良い',
    category: '思考実験',
  },
  {
    topic: 'なれるなら、小人よりも巨人が良い',
    positionA: 'なれるなら巨人が良い',
    positionB: 'なれるなら小人が良い',
    category: '思考実験',
  },
  {
    topic: '友達になるなら、ロボットよりも宇宙人が良い',
    positionA: '友達になるなら宇宙人が良い',
    positionB: '友達になるならロボットが良い',
    category: '思考実験',
  },
  {
    topic: '探検するなら、宇宙よりも深海が良い',
    positionA: '探検するなら深海が良い',
    positionB: '探検するなら宇宙が良い',
    category: '思考実験',
  },
  {
    topic: '新しい惑星に住むなら、海に覆われた惑星よりも森に覆われた惑星が良い',
    positionA: '新しい惑星に住むなら森に覆われた惑星が良い',
    positionB: '新しい惑星に住むなら海に覆われた惑星が良い',
    category: '思考実験',
  },
  {
    topic: '無人島に一つ持っていくなら、道具よりも仲間が良い',
    positionA: '無人島に持っていくなら仲間が良い',
    positionB: '無人島に持っていくなら道具が良い',
    category: '思考実験',
  },
  {
    topic: '世界から一つなくすなら、悲しみよりも怒りが良い',
    positionA: '世界からなくすなら怒りが良い',
    positionB: '世界からなくすなら悲しみが良い',
    category: '思考実験',
  },
  {
    topic: '未来社会の運営は、人間よりもAIが良い',
    positionA: '未来社会の運営はAIが良い',
    positionB: '未来社会の運営は人間が良い',
    category: '思考実験',
  },
  {
    topic: '学ぶなら、教わるよりも独学が良い',
    positionA: '学ぶなら独学が良い',
    positionB: '学ぶなら人に教わるのが良い',
    category: '仕事・学び',
  },
  {
    topic: 'メモは、デジタルよりも手書きが良い',
    positionA: 'メモは手書きが良い',
    positionB: 'メモはデジタルが良い',
    category: '仕事・学び',
  },
  {
    topic: '授業は、オンラインよりも対面が良い',
    positionA: '授業は対面が良い',
    positionB: '授業はオンラインが良い',
    category: '仕事・学び',
  },
  {
    topic: '伸ばすなら、苦手を克服するよりも得意を伸ばすのが良い',
    positionA: '得意を伸ばすのが良い',
    positionB: '苦手を克服するのが良い',
    category: '仕事・学び',
  },
  {
    topic: '目指すなら、一つを極める専門家よりも何でもこなせる万能型が良い',
    positionA: '目指すなら何でもこなせる万能型が良い',
    positionB: '目指すなら一つを極める専門家が良い',
    category: '仕事・学び',
  },
  {
    topic: '目標は、大きな目標を一つ掲げるよりも小さな目標を積み重ねるのが良い',
    positionA: '小さな目標を積み重ねるのが良い',
    positionB: '大きな目標を一つ掲げるのが良い',
    category: '仕事・学び',
  },
  {
    topic: '新しいことは、しっかり学んでから始めるよりもまずやってみるのが良い',
    positionA: '新しいことはまずやってみるのが良い',
    positionB: '新しいことはしっかり学んでから始めるのが良い',
    category: '仕事・学び',
  },
  {
    topic: '働くなら、オフィス勤務よりもリモートワークが良い',
    positionA: '働くならリモートワークが良い',
    positionB: '働くならオフィス勤務が良い',
    category: '仕事・学び',
  },
  {
    topic: 'キャリアは、幅広い技能を持つよりも専門性を高めるのが良い',
    positionA: 'キャリアは専門性を高めるのが良い',
    positionB: 'キャリアは幅広い技能を持つのが良い',
    category: '仕事・学び',
  },
  {
    topic: '仕事を選ぶなら、高収入よりも自由時間の多さが良い',
    positionA: '仕事を選ぶなら自由時間の多さが良い',
    positionB: '仕事を選ぶなら高収入が良い',
    category: '仕事・学び',
  },
  {
    topic: 'リーダーは、話し合いを重視する人よりも素早く決断する人が良い',
    positionA: 'リーダーは素早く決断する人が良い',
    positionB: 'リーダーは話し合いを重視する人が良い',
    category: '仕事・学び',
  },
  {
    topic: '友達は、広く浅くよりも狭く深くが良い',
    positionA: '友達は狭く深くが良い',
    positionB: '友達は広く浅くが良い',
    category: '人間関係',
  },
  {
    topic: '連絡は、メッセージよりも電話が良い',
    positionA: '連絡は電話が良い',
    positionB: '連絡はメッセージが良い',
    category: '人間関係',
  },
  {
    topic: 'プレゼントは、希望を聞くよりもサプライズが良い',
    positionA: 'プレゼントはサプライズが良い',
    positionB: 'プレゼントは希望を聞いて選ぶのが良い',
    category: '人間関係',
  },
  {
    topic: '相談されたら、アドバイスするよりも聞き役に徹するのが良い',
    positionA: '相談されたら聞き役に徹するのが良い',
    positionB: '相談されたらアドバイスするのが良い',
    category: '人間関係',
  },
  {
    topic: '誕生日は、少人数で静かに祝うよりもみんなで盛大に祝うのが良い',
    positionA: '誕生日はみんなで盛大に祝うのが良い',
    positionB: '誕生日は少人数で静かに祝うのが良い',
    category: '人間関係',
  },
  {
    topic: '初対面では、話し役よりも聞き役に回るのが良い',
    positionA: '初対面では聞き役に回るのが良い',
    positionB: '初対面では話し役になるのが良い',
    category: '人間関係',
  },
  {
    topic: '悩みは、自分で整理するよりも人に話すのが良い',
    positionA: '悩みは人に話すのが良い',
    positionB: '悩みは自分で整理するのが良い',
    category: '人間関係',
  },
  {
    topic: 'スマートフォンは、iPhoneよりもAndroidが良い',
    positionA: 'スマートフォンはAndroidが良い',
    positionB: 'スマートフォンはiPhoneが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'スマホは、コンパクトよりも大画面が良い',
    positionA: 'スマホは大画面が良い',
    positionB: 'スマホはコンパクトが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '新製品は、評判を待つよりもすぐ買うのが良い',
    positionA: '新製品はすぐ買うのが良い',
    positionB: '新製品は評判を待ってから買うのが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '車は、自動運転に任せるよりも自分で運転する方が良い',
    positionA: '車は自分で運転する方が良い',
    positionB: '車は自動運転に任せる方が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '家電は、多機能よりもシンプルなものが良い',
    positionA: '家電はシンプルなものが良い',
    positionB: '家電は多機能なものが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'ソフトウェアの料金は、買い切りよりもサブスクリプションが良い',
    positionA: 'ソフトウェアの料金はサブスクリプションが良い',
    positionB: 'ソフトウェアの料金は買い切りが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '買い物をするなら、実店舗よりもオンラインショップが良い',
    positionA: '買い物をするならオンラインショップが良い',
    positionB: '買い物をするなら実店舗が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'ゲームをするなら、家庭用ゲーム機よりもゲーミングPCが良い',
    positionA: 'ゲームをするならゲーミングPCが良い',
    positionB: 'ゲームをするなら家庭用ゲーム機が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'パソコンのOSは、MacよりもWindowsが良い',
    positionA: 'パソコンのOSはWindowsが良い',
    positionB: 'パソコンのOSはMacが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'SNSを利用するなら、匿名よりも実名が良い',
    positionA: 'SNSを利用するなら実名が良い',
    positionB: 'SNSを利用するなら匿名が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '文字入力は、タッチ操作よりも物理キーボードが良い',
    positionA: '文字入力は物理キーボードが良い',
    positionB: '文字入力はタッチ操作が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'スマートフォンの通知は、すべて受け取るよりも必要なものだけが良い',
    positionA: 'スマートフォンの通知は必要なものだけが良い',
    positionB: 'スマートフォンの通知はすべて受け取るのが良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: 'イヤホンは、有線よりもワイヤレスが良い',
    positionA: 'イヤホンはワイヤレスが良い',
    positionB: 'イヤホンは有線が良い',
    category: 'テクノロジー・買い物',
  },
  {
    topic: '旅に出るなら、仲間と行くよりも一人旅が良い',
    positionA: '旅は一人旅が良い',
    positionB: '旅は仲間と行くのが良い',
    category: '旅行',
  },
  {
    topic: '宿は、ホテルよりも温泉旅館が良い',
    positionA: '宿は温泉旅館が良い',
    positionB: '宿はホテルが良い',
    category: '旅行',
  },
  {
    topic: '旅行は、海外よりも国内が良い',
    positionA: '旅行は国内が良い',
    positionB: '旅行は海外が良い',
    category: '旅行',
  },
  {
    topic: 'お土産は、雑貨よりも食べ物が良い',
    positionA: 'お土産は食べ物が良い',
    positionB: 'お土産は雑貨が良い',
    category: '旅行',
  },
  {
    topic: '旅は、名所を巡るよりも一か所でゆったり滞在するのが良い',
    positionA: '旅は一か所でゆったり滞在するのが良い',
    positionB: '旅は名所を巡るのが良い',
    category: '旅行',
  },
  {
    topic: '旅先は、山よりも海が良い',
    positionA: '旅先は海が良い',
    positionB: '旅先は山が良い',
    category: '旅行',
  },
  {
    topic: '旅行は、自由に行動するよりも計画を立てるのが良い',
    positionA: '旅行は計画を立てるのが良い',
    positionB: '旅行は自由に行動するのが良い',
    category: '旅行',
  },
  {
    topic: '観光するなら、自由行動よりもガイドツアーが良い',
    positionA: '観光するならガイドツアーが良い',
    positionB: '観光するなら自由行動が良い',
    category: '旅行',
  },
];
